### ISSUE TITLE
cannot load the frontend after building the production file using react build scripts, I have been stuck with this all day , if anyone can help with it , please write the solution in the comments

### ISSUE THREAD

**Issue by bary24** [odziem/nasa-project#3]
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.ai (main.d5cd5a52.js:2:329928)
    at t.useState (main.d5cd5a52.js:2:422732)
    at main.d5cd5a52.js:2:471593
    at oi (2.acf50103.chunk.js:2:164940)
    at Wu (2.acf50103.chunk.js:2:217398)
    at Pl (2.acf50103.chunk.js:2:204572)
    at Sl (2.acf50103.chunk.js:2:204500)
    at Ol (2.acf50103.chunk.js:2:204363)
    at yl (2.acf50103.chunk.js:2:201329)
    at 2.acf50103.chunk.js:2:150708
uu @ react-dom.production.min.js:216

**Comment by valentinesamuel** [comment]
have you tried reinstalling the node_modules folder 
OR
you compare your code with that of the instructor

**Comment by ShohanMir** [comment]
Provably you importing useEffect from the wrong place. Import useEffect:
`import React, {useEffect} from 'react';`

**Comment by JamesHHoustonII** [comment]
This is still an issue, anyone find an answer?
